### ISSUE TITLE
Docs with commas being cut off

### ISSUE THREAD

**Issue by mgold** [elm-lang/package.elm-lang.org#121]
I have a sentence with a comma in the docs after some `@docs` declarations. The line as written in the Elm source, the documentation.json generated locally, and the one I get over the network, is

>You may set an animation's duration or speed but not both, since one determines the other.

But it's being displayed as

>You may set an animation's duration or speed but not both

The issue seems to be [here](https://github.com/elm-lang/package.elm-lang.org/blob/1711c445c726b6b96f8c511f58f2052874c900dd/src/frontend/Component/PackageDocs.elm#L236) in that it assumes all commas after the first `@docs` are part of the docs syntax. Instead is should look for commas line by line.

I'm not sure if this was broken by the revamp or not.

Originally reported [here](https://groups.google.com/d/msg/elm-dev/G9FGTAyHATk/8gRHFb1BBAAJ). cc @evancz You wanted to be tagged.

**Comment by evancz** [comment]
I wanted to be tagged on the PR ;)

**Comment by mgold** [comment]
Oh doy! I'll figure it out in the next few days!

**Comment by rtfeldman** [comment]
Ha! I was wondering if this was a bug in http://package.elm-lang.org/help/docs-preview - guess not. :smile:

**Comment by mgold** [comment]
@rtfeldman If you have more examples of the problems this is causing, please post them on #127 so it can be merged.

**Comment by evancz** [comment]
Has anyone shared a http://sscce.org of this anywhere yet? I still have not seen one. I want to see the exact documentation comment. I keep linking to http://sscce.org because it is actually extremely helpful to get things in this format. You know all the details, but it is very hard to figure things out just from prose and following links to massive threads.

**Comment by evancz** [comment]
I ask because (1) I think there is a much simpler way to fix this than the proposed fix. If we had even one http://sscce.org, it'd be much easier to figure this out without doing a ton of exploration on my own. I also ask because (2) we need to have discipline about having http://sscce.org in all issues and PRs. No matter how experienced OP is, an issue that has an http://sscce.org is better and easier than one that does not. I do not see a viable substitute for this, or why we would want a substitute.

**Comment by rtfeldman** [comment]
Can I propose adding a label of `blocked pending a http://sscce.org` to these?

In a lot of cases, I come across something that I think is worth publicly recording so it doesn't get lost (and maybe will shed light on a problem someone else is having)...but while I'm willing to devote 30 seconds to pasting in what went wrong and typing up a paragraph explaining it, I just don't care enough about the symptom to context switch to it for 10-15 minutes to make a sscce of it.

I'd like to continue publicly posting issues I don't care enough about to sscce up (rather than discarding useful data), but in a way where there can be an explicit understanding that it's not going to get worked on until someone does that.

Does that seem reasonable? Or would it be better if I more often said "don't care enough to sscce it, so not going to post it" and kept the issue to myself? I don't feel strongly about it either way, but this conflict comes up a lot, so I'd like to try for a more systematic solution.

**Comment by evancz** [comment]
I have a "no sscce" tag on error-message-catalog and it is nice. If something doesn't have it, it is basically useless noise. If OP (or someone) can't make one, I don't see how anyone can make a fix that can be easily vetted.

I can add that tag to these repos. I'm working on outlining clear "curation" guidelines for folks that want to help with this, probably updating [these](https://github.com/elm-lang/elm-plans/blob/master/CONTRIBUTING.md) and making them easier to find.

**Comment by mgold** [comment]
Prior to Richard's docs previewer, there was really no way to test an SSCCE without releasing a package. But now there is.

**[Here is an SSCCE](https://gist.github.com/mgold/ad05f8c03b6b74ca5798)**. The important part is the bit at the bottom, which says its about to have a comma, and then gets cut off. I have included the generated docs file, but you can recreate for yourself from the Elm source if you like. (You just have to list the module as exposed.)

This can also function as an acceptance test, so I have included two definitions to test the multi-line `@docs` case brought up in the PR.

**Comment by rtfeldman** [comment]
(side note: I definitely cannot take credit for the docs previewer, which totally rules - I believe @burabure made it, yeah?)

**Comment by burabure** [comment]
Thanks for tagging me @rtfeldman! I don't think the package preview is the issue since I'm using the same parsers that the docs are using, but you never know ;D

Thanks for the SSCCE @mgold, I'll take a look at this and see if I can come up with something =)

**Comment by mgold** [comment]
@burabure, thanks for making the package preview! I didn't mean that it's the source of the bug, but rather that it made an SSCCE much more practical. There is already a PR, #127.

**Comment by evancz** [comment]
Seeing the root issue, it feels like the fix should be a one line thing. I
think it'd be cool for someone else to try that and either make things
simpler or verify that it cannot be done.

On Sunday, December 27, 2015, Max Goldstein <notifications@github.com>
wrote:

> @burabure <https://github.com/burabure>, thanks for making the package
> preview! I didn't mean that it's the source of the bug, but rather that it
> made an SSCCE much more practical. There is already a PR, #127
> <https://github.com/elm-lang/package.elm-lang.org/pull/127>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elm-lang/package.elm-lang.org/issues/121#issuecomment-167444897>
> .
>


-- 
Sent from Gmail Mobile

**Comment by mgold** [comment]
By all means, someone else have a shot at it.

**Comment by burabure** [comment]
@evancz It's not a one-liner but handles complex cases nicely. https://github.com/elm-lang/package.elm-lang.org/pull/150

I think the code could get more declarative/cleaner, @rtfeldman / @mgold If you have some ideas I'm happy to get constructive criticism

**Comment by evancz** [comment]
Should be resolved, thanks everyone!
