### ISSUE TITLE
Updating elm-webgl and elm-linear-algebra

### ISSUE THREAD

**Issue by nphollon** [elm-lang/package.elm-lang.org#143]
@johnpmayer has been absent from Github for three months, and his [elm-linear-algebra](https://github.com/johnpmayer/elm-linear-algebra) and [elm-webgl](https://github.com/johnpmayer/elm-webgl) packages lie dormant. This has become an bigger issue now that Elm 0.16 has been released.

I would like to get up-to-date versions of his packages released as quickly as possible. Perhaps somebody with write access could simply bump the version numbers?

If all else fails, I would be willing to take ownership of them, but I wanted to check here before forking and trying to go through the native review process.

**Comment by simonh1000** [comment]
We had this issue with elm-history too, and that gave rise to the elm-community repos - you might want to enquire with Ryan about shifting these there too

**Comment by rgrempel** [comment]
Both elm-linear-algebra and elm-webgl are native modules, so it would be easier if @johnpmayer could update them -- since his version of the modules are already whitelisted.

I see that elm-linear-algebra has a couple of [pull](https://github.com/johnpmayer/elm-linear-algebra/pull/14) [requests](https://github.com/johnpmayer/elm-linear-algebra/pull/14) for Elm 0.16, about a week old.

Perhaps someone could create an issue on elm-webgl as well (though I expect that if @johnpmayer deals with the one he'll probably deal with the other).

If these are orphans, then the decision tree would be:

1. Is someone willing to take on maintenance of them?

2. If so, then would they like to do it in their own github account, or inside elm-community's? Doing it on your own is fine, of course -- the only reason to do it inside elm-community would be to immediately have other people with write access as well (to avoid future orphan situations).

3. If not, elm-community could take over maintenance by itself.

The native review process is about the same either way (inside elm-community or outside), though it's possible that doing it inside elm-community might expedite it a little bit.

Anyway, what I'd suggest is giving @johnpmayer a little more time to respond, and then see what the best option seems to be.

**Comment by mgold** [comment]
I saw John on the mailing list a few days ago, maybe he'll get to it. Otherwise I like that plan.

**Comment by nphollon** [comment]
I think that sounds good. Really glad we are keeping an eye on orphaned projects!

**Comment by rgrempel** [comment]
I have now forked these two in @elm-community, and given @nphollon and @fredcy collaborator status on them.

**Comment by mgold** [comment]
Yeah, I've noticed that hiccup. I wonder if the packager can somehow be made more aware of forking? Except that sometimes the same name is used for [unrelated libraries](https://groups.google.com/d/msg/elm-discuss/DmEMbgFPluY/7xSx3kAdCgAJ).

**Comment by nphollon** [comment]
Now that @rgrempel has forked these, we can continue this discussion over at @elm-community
