### ISSUE TITLE
Native review for elm-community/elm-linear-algebra

### ISSUE THREAD

**Issue by nphollon** [elm-lang/package.elm-lang.org#149]
johnpmayer/elm-linear-algebra appeared to be an orphan, so elm-community adopted it. The new repo is: https://github.com/elm-community/elm-linear-algebra.

For more context, see #143 and https://github.com/elm-community/Manifesto/issues/2

I am not sure what the best way to handle the version numbering is. The package manager will want us to reset to 1.0.0, correct?

If this gets approved, we will do a similar treatment for elm-webgl.

**Comment by jvoigtlaender** [comment]
@evancz, can you whitelist `elm-community/elm-linear-algebra`? Its only changes over the already whitelisted `johnpmayer/elm-linear-algebra` are: https://github.com/johnpmayer/elm-linear-algebra/compare/2.0.2...elm-community:master. That is, there are no changes to code at all.

And as you observed [here](https://github.com/elm-lang/elm-lang.org/issues/462#issuecomment-166230270), an update of this library to be compatible with Elm 0.16 is needed to make stuff on the Elm homepage work again.

**Comment by evancz** [comment]
Added with the understanding that if folks want to start making MINOR or MAJOR changes, I want them to run it by me or John. The only reason these things are on the whitelist is because John and I talked through exactly how things worked and I trusted him to keep making good decisions. I don't really know who is part of elm-community or what the goals are, so I'd want to build that relationship before doing a ton of stuff to John's work.
