### ISSUE TITLE
The package list contain packages that no longer exist

### ISSUE THREAD

**Issue by pdamoc** [elm-lang/package.elm-lang.org#233]
The following packages give a 404 when trying to access their GitHub repository: 
```
RomanErnst/updated-list
omarroth/elm-dom
omarroth/elm-parts
spisemisu/elm-merkletree
spisemisu/elm-sha
spisemisu/elm-utf8
```

Attempting to install any of the packages listed above using `elm-package` results in garbage pushed onto the user console (the raw html of the 404 page).

**Comment by evancz** [comment]
With 0.19 I am filtering some things out as listed [here](https://github.com/elm-lang/package.elm-lang.org/blob/dev/migration/Migrate.hs#L84-L117), so the first three are not going to be alive anymore.

I guess the other three work again? Not sure.

Longer term, we will host the code somewhere besides GitHub so that things can never disappear.
