### ISSUE TITLE
Hyperlink types in type signatures

### ISSUE THREAD

**Issue by agrafix** [elm-lang/package.elm-lang.org#53]
It would be very useful if types in type signatures would be hyperlinked to their definition (as on hackage or the purescript packages page).

**Comment by jvoigtlaender** [comment]
See https://groups.google.com/d/msg/elm-discuss/7JJyM1UkXsQ/vRGGaKQMayAJ.

**Comment by jvoigtlaender** [comment]
I've implemented this: https://github.com/elm-lang/package.elm-lang.org/pull/60

**Comment by jvoigtlaender** [comment]
@agrafix, maybe close this issue, or replace it with something describing what is desirable on top of #60 (which has been merged and is live on the package site).

**Comment by agrafix** [comment]
Cool, thanks for your work! It does not work everywhere yet though? ( http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Regex#find ). And it does not work across packages yet, correct? This is probably a compiler limitation?

**Comment by jvoigtlaender** [comment]
1. It only works (and will only ever work) for packages that are published with the now current Elm suite or later ones. The example package you give was either uploaded a while ago, or was uploaded recently but with outdated tools. The difference can be seen in the last entry of http://package.elm-lang.org/packages/elm-lang/core/2.1.0/docs/Regex.json. Whenever such a file has `"generated-with-elm-version": "old"`, it won't profit from the type hyperlinking.

2. And yes, it does not work across packages, and indeed that is because there is not enough information in the `.json` files. It would have to be put there by the compiler or upload tool. Prior to that, some design decisions would have to be made. Quoting Evan from the mailing list message already linked to above:

> Doing it across packages is harder, because we do not have the package annotations there right now. So I'd say do it within first, then we can think about questions like, "when linking to another package, which version do I link to? Highest in declared bounds? The one the author was using?"

**Comment by evancz** [comment]
Agree with @jvoigtlaender, if further things are desired, open an issue describing it so we have a clean issue to look at.
