### ISSUE TITLE
Native review for suryagaddipati/elm-html

### ISSUE THREAD

**Issue by suryagaddipati** [elm-lang/package.elm-lang.org#68]
Hi,

I am trying to publish https://github.com/suryagaddipati/elm-html/ 

This repository is based on Cannonical [Elm-html](https://github.com/evancz/elm-html/) but uses [Incremental Dom](https://github.com/google/incremental-dom)
instead of Virtual Dom.

This is to workaround this virtual dom issue https://github.com/evancz/virtual-dom/issues/14

**Comment by laszlopandy** [comment]
Hi. I like your library but I think you should change it to elm-html-incremental or something which indicates that it is somehow different from elm-html.

1. I understand that you want it to be a drop in replacement, and that will still work if the Elm module names are the same. But the package should have a different name.
2. I think you should rename VirtualDom.elm to IncrementalDom.elm. Because most people only import Html (and not VirtualDom) this will not stop your library from being a drop in replacement. I'm curious, is your VirtualDom.elm directly compatible, with the same set of functions as Evan's VirtualDom?

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-).

I would recommend getting more involved on elm-dev or on the Elm slack channel and talking to folks there. If you have rendering benchmarks for this thing, it'd be good to compare the two approaches. I think it'd make sense to do that before introducing this stuff.
