### ISSUE TITLE
Native review for nphollon/record-builder

### ISSUE THREAD

**Issue by nphollon** [elm-lang/package.elm-lang.org#83]
https://github.com/nphollon/record-builder

This library creates a record from a dictionary. The one public function is pure but does carry the risk of a runtime error (if the dictionary's fields have a different type than the record's fields). I look forward to your feedback.

**Comment by evancz** [comment]
I don't think this is a good candidate because it permits runtime errors. This is something we are actively working to avoid entirely.

If you give a prototype like `4` or `"hello"` I suspect things just crash, same as if you give records with non-uniform types.

@elm-lang/packages, let's get the 2 other reviews.

**Comment by nphollon** [comment]
@evancz I think I could eliminate the runtime errors entirely without too much extra effort, if that is the only thing preventing this from being accepted. But I agree that a core language enhancement would be better. How far on the horizon do you think the `deriving` functionality is?

In its current state, the library is not as fragile as you suspect. All of the examples you mention result in `Nothing` being returned.

**Comment by evancz** [comment]
Aside from runtime errors and magic types that may never be expressible in pure Elm, I don't really understand why you want this library. What's the use case you have in mind? My intuition would be that this would almost exclusively be used in place of "the right thing".

I don't want to do too much more review of this myself. I would like to hear from some of the other @elm-lang/packages reviewers.

**Comment by laszlopandy** [comment]
I would not approve without removing all the runtime errors. I am also curious to see what the use case is, and if it's very useful in practice.

**Comment by nphollon** [comment]
I will get rid of the runtime errors.

I've found that I often use data types with a fixed set of keys and values with a uniform type. The dictionary and the record have utility at different points in the life-cycle of the program.

When I am initializing the model, storing the data in a dictionary allows it to be easily mapped and manipulated. But once I pass the model to `foldp`, the data becomes read-only. A record is ideal in this situation because the required keys are guaranteed to be present. Using `Dict.get "bar" >> Maybe.withDefault` is cumbersome because the best time to handle the possibility missing data is long before I need to access it.

This is a scenario that I have run into a few times. There are, of course, ways of solving it in pure Elm for specific cases, but as my projects evolve and the record type definitions change, the extra cost of maintaining `map` functions or initializers becomes noticeable.

Now, I've seen my fair share of terrible reflection-riddled Ruby and Java, so I am prepared to have this library denounced as a monstrosity :-P But I'd appreciate the opportunity to experiment with it, once there is no risk of runtime errors.

**Comment by rtfeldman** [comment]
Now that I understand the use case, let me propose an alternative that does not require `Native`.

I write a lot of decoders for this exact use case, using this style: https://gist.github.com/rtfeldman/255c5dbbf517bfda1118

That's not significantly more verbose than the sample use cases for `build`; the only comparative drawback is that what you get back works on a `Value` or a `String` but not a `Dict String a`.

I am about to head out the door, so I'm not going to attempt an implementation, but conceptually I don't see a reason you couldn't write an `andMap` (or `|:` for brevity) implementation for `Dict` that gives you back a `Result a` instead of a `Decoder`, and which you could then use in the style of that gist to partially apply your way through a type alias constructor function until you got back `Result String record` representing either what you wanted or an error message string explaining which expected `Dict` key was missing.

**Comment by nphollon** [comment]
Sorry I've let this lie dormant for so long. I will withdraw my review request, since I've come around to agreeing that it's probably not very useful.

@rtfeldman Thanks for the suggestion. I wasn't familiar with the JSON modules in the core library, and they actually turned out to fit my use case pretty well.
